modLoader="javafml"
license="MIT"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/yurisuika/Sap/issues"

[[mods]]
modId="sap"
version="0.3.0"
displayName="Sap"
updateJSONURL="https://raw.githubusercontent.com/yurisuika/Sap/blob/master/updates.json"
displayURL="https://github.com/yurisuika/Sap"
logoFile="pack.png"
credits="yurisuika"
authors="yurisuika"
description="Sap - a realistic flora mod."

[[dependencies.sap]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.sap]]
modId="abnormals_core"
mandatory=true
versionRange="[3.0.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sap]]
modId="terraforged"
mandatory=true
versionRange="[0.1.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sap]]
modId="optifine"
mandatory=false
versionRange="[1.0.0,)"
ordering="BEFORE"
side="BOTH"
